# Generated by Django 5.1.2 on 2024-10-24 02:48

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="services",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Provider",
                    models.CharField(max_length=50, verbose_name="Provider Name"),
                ),
                ("Category", models.CharField(max_length=20, verbose_name="Category")),
                ("Description", models.CharField(blank=True, max_length=120)),
                ("contact", models.EmailField(max_length=254, verbose_name="Email")),
            ],
        ),
        migrations.CreateModel(
            name="task_genieuser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "Phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="appointments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date", models.DateTimeField()),
                (
                    "services",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services.services",
                    ),
                ),
            ],
        ),
    ]
