# Generated by Django 5.1.2 on 2024-10-24 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task_genieuser", old_name="first_name", new_name="name",
        ),
        migrations.RenameField(
            model_name="task_genieuser", old_name="last_name", new_name="password",
        ),
        migrations.RemoveField(model_name="task_genieuser", name="Phone",),
    ]
