# Generated by Django 5.1.2 on 2024-10-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_rename_first_name_task_genieuser_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task_genieuser",
            name="password",
            field=models.CharField(max_length=5),
        ),
    ]
